ZjazdRodzinny/Controllers/GalleryController.cs
using System.IO;
using ZjazdRodzinny.Models;
using System.Web.Mvc;

namespace ZjazdRodzinny.Controllers
{
    [Authorize]
    public class GalleryController : ExceptionController
    {
        public ActionResult Index()
        {
            var directories = Directory.GetDirectories(Server.MapPath(Url.Content("~/assets/img/Photos/")));

            ListGalleryViewModel model = new ListGalleryViewModel();
            model.Titles = new System.Collections.Generic.List<string>();

            foreach (string path in directories)
                model.Titles.Add(path);

            return View(model);
        }

        public ActionResult Video()
        {
            return View();
        }
    }
}

ZjazdRodzinny/Views/Shared/Navigation/_NavigationBar.cshtml
<!--Header upper region-->
<div class="header-upper">

</div>
<div data-toggle="sticky" class="sticky is-sticky">

    <!--Header & Branding region-->
    <div class="header">
        <!-- all direct children of the .header-inner element will be vertically aligned with each other you can override all the behaviours using the flexbox utilities (flexbox.htm) All elements with .header-brand & .header-block-flex wrappers will automatically be aligned inline & vertically using flexbox, this can be overridden using the flexbox utilities (flexbox.htm) Use .header-block to stack elements within on small screen & "float" on larger screens use .flex-first or/and .flex-last classes to make an element show first or last within .header-inner or .headr-block elements -->
        <div class="header-inner container">
            <!--branding/logo -->
            <div class="header-brand flex-first">
                <a class="header-brand-text" href="@Url.Action("Index","Home")" title="Strona startowa">
                    <h1>
                        Rodzina<span>Co</span>Rok!
                    </h1>
                </a>
            </div>
            <!-- other header content -->
            <div class="header-block flex-last">
                <!-- mobile collapse menu button - data-toggle="collapse" = default BS menu - data-toggle="jpanel-menu" = jPanel Menu - data-toggle="overlay" = Overlay Menu -->
                <a href="#top" class="btn btn-link btn-icon header-btn float-right hidden-lg-up" data-toggle="jpanel-menu" data-target=".navbar-main" data-direction="right"> <i class="fa fa-bars"></i> </a>
            </div>

            <div class="navbar navbar-toggleable-md">
                <!--everything within this div is collapsed on mobile-->
                <div class="navbar-main collapse">
                    <!--main navigation-->
                    <ul class="nav navbar-nav float-lg-right dropdown-effect-fade">
                        <!-- Zdjęcia -->
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Gallery")" class="nav-link" id="zdjecia-link" data-toggle="dropdown" data-hover="dropdown">Zdjęcia</a>
                        </li>
                        <!-- O nas -->
                        <li class="nav-item">
                            <a href="@Url.Action("About","Home")" class="nav-link" id="about-drop">O nas</a>
                        </li>
                    </ul>
                </div>
                <!--/.navbar-collapse -->
            </div>
        </div>
    </div>
</div>